name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run gomarklint Action
        uses: ./
        with:
          args: testdata

  test-comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run gomarklint Action with PR comment
        uses: ./
        with:
          args: testdata
          comment-on-pr: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
