name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run gomarklint Action
        uses: ./
        with:
          args: testdata
